name: tea_time
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  fl_chart: ^0.41.0
  flutter_localizations:
    sdk: flutter
  collection: any
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  table_calendar: ^3.0.9
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_translation: ^0.18.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/config/.env
    - assets/data/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
